# Splunk Connect for SNMP poller
snmp:
  mibs_server: "http://mib-server-host:5000"

celery:
  broker:
    type: "rabbitmq"

# Sample Configuration file
ipv4: True
ipv6: False
communities:
  v1:
    - public
    - "my-area"

profiles:
  router:
    varBinds: ['sysDescr', 'uptime', 'name', 'routingTable']
  atm:
    varBinds: ['sysDescr', 'cashLeft', 'transactionCount', '1.2.2.2.2.2...2']