# Splunk Connect for SNMP poller
# Sample Configuration file
ipv4: True
ipv6: False
communities:
  v1:
    - public
    - "my-area"

profiles:
  router:
    varBinds: ['uptime', 'name', 'routingTable']
  atm:
    varBinds: ['cashLeft', 'transactionCount']